# PW SKILLS

## Assignment Questions :


In [1]:
import numpy as np

list_ = [ '1' , '2' , '3' , '4' , '5' ]

array_list = np.array(object = list_)

### Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.
### Answer : 

In [2]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

print("Data type of list_:", type(list_))
print("Data type of array_list:", type(array_list))


Data type of list_: <class 'list'>
Data type of array_list: <class 'numpy.ndarray'>


### Q2. Write a code to print the data type of each and every element of both the variables list_ and arra_list.
### Answer : We can use a loop to iterate through each element in list_ and array_list and print the data type of each element. Here's the code for that:

In [3]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

# Print data types of elements in list_
print("Data types of elements in list_:")
for element in list_:
    print(type(element))

# Print data types of elements in array_list
print("\nData types of elements in array_list:")
for element in array_list:
    print(type(element))


Data types of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data types of elements in array_list:
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


### Q3. Considering the following changes in the variable, array_list:

array_list = np.array(object = list_, dtype = int)

### Will there be any difference in the data type of the elements present in both the variables, list_ and arra_list? If so then print the data types of each and every element present in both the variables, list_ and arra_list.
### Answer : Yes, there will be a difference in the data types of the elements present in list_ and array_list after the modification. The dtype=int parameter in np.array() will force the elements in array_list to be of integer type.

### Here's the code to print the data types of each element in both list_ and array_list after the modification:



In [4]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_, dtype=int)

# Print data types of elements in list_
print("Data types of elements in list_:")
for element in list_:
    print(type(element))

# Print data types of elements in array_list
print("\nData types of elements in modified array_list:")
for element in array_list:
    print(type(element))


Data types of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data types of elements in modified array_list:
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>


In [5]:
import numpy as np

num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

num_array = np.array(object = num_list)

In [6]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

### Q4. Write a code to find the following characteristics of variable, num_array:

### (i)	 shape

### (ii) size
### Answer : 

In [7]:
# (i) Shape of the array
print("Shape of the array:")
print(num_array.shape)

# (ii) Size of the array
print("\nSize of the array:")
print(num_array.size)

Shape of the array:
(2, 3)

Size of the array:
6


### Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.

### [Hint: The size of the array will be 9 and the shape will be (3,3).]
### Answer :

In [8]:
data=np.random.randint(0,1,(3,3))

In [9]:
data

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

### Q6. Create an identity matrix of shape (5,5) using numpy functions?

### [Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]
### Answer : 

In [10]:
import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.eye(5)

# Print the created identity matrix
print("5x5 Identity Matrix:")
print(identity_matrix)


5x5 Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


# OR

In [12]:
data1=np.diag([1,1,1,1,1,]) 

In [13]:
data1

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])